name = "roonging-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *", "0 */6 * * *", "0 15 * * 0", "0 15 * * *"]

[vars]
DISCORD_APP_ID = "1500717088984010883"
DISCORD_PUBLIC_KEY = "e39c71aa12d8af890a14cf7e97fd1de64cdcc43e9d5f733d3c4ea936ed98c8c9"
# DISCORD_BOT_TOKEN은 Cloudflare Dashboard Secrets에 추가 (wrangler secret put DISCORD_BOT_TOKEN)
